mv .ackrc ackrc
mv .aliases aliases
mv .bash_profile bash_profile
mv .bashrc bashrc
mv .editrc editrc
mv .git git
mv .gitconfig gitconfig
mv .gitexclude gitexclude
mv .gitignore gitignore
mv .gitmodules gitmodules
mv .gvimrc gvimrc
mv .inputrc inputrc
mv .irbrc irbrc
mv .profile profile
mv .screenrc screenrc
mv .tmux.conf tmux.conf
mv .vim vim
mv .vimrc vimrc
mv .zprofile zprofile
mv .zshenv zshenv
mv .zshrc zshrc
